name: Build and Publish

on:
  release:
    types: [published]

jobs:
  publish-chrome-store:
    runs-on: ubuntu-latest
    # Only run for minor and major releases (not patches from chore/docs/etc)
    if: |
      github.event.release.tag_name &&
      (contains(github.event.release.body, '### Features') || 
       contains(github.event.release.body, '### Bug Fixes') ||
       contains(github.event.release.body, 'BREAKING CHANGE'))
    
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install
      
      - name: Build extension
        run: npm run build
      
      - name: Get version
        id: version
        run: echo "VERSION=$(grep '\"version\"' manifest.json | sed 's/.*\"version\": \"\\(.*\\)\".*/\\1/')" >> $GITHUB_OUTPUT
      
      - name: Upload to Chrome Web Store
        uses: trmcnvn/chrome-addon@v2
        with:
          extension: ${{ secrets.CHROME_EXTENSION_ID }}
          zip: ./build/line-highlighter-v${{ steps.version.outputs.VERSION }}.zip
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}