name: Release Please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node
          package-name: line-highlighter
          target-branch: master
          pull-request-title-pattern: "Release v${version}"
          pull-request-header: "Release Notes"
          
      # The following steps only run if a release was created
      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}
      
      - name: Build Extension
        if: ${{ steps.release.outputs.release_created }}
        run: |
          npm install
          npm run build
      
      - name: Upload Release Asset
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./build/line-highlighter-v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}.zip
          asset_name: line-highlighter-v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}.zip
          asset_content_type: application/zip